# Generated by Django 6.0.4 on 2026-06-02 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Колір')),
            ],
            options={
                'verbose_name': 'Колір',
                'verbose_name_plural': 'Кольори',
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Виробник')),
            ],
            options={
                'verbose_name': 'Виробник',
                'verbose_name_plural': 'Виробники',
                'db_table': 'manufacturer',
            },
        ),
        migrations.CreateModel(
            name='WireType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва типу')),
            ],
            options={
                'verbose_name': 'Тип дроту/кабелю',
                'verbose_name_plural': 'Типи дротів та кабелів',
                'db_table': 'wire_type',
            },
        ),
        migrations.CreateModel(
            name='WireVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cores', models.PositiveSmallIntegerField(verbose_name='Кількість жил')),
                ('mm2', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Переріз (мм.кв)')),
                ('shape', models.CharField(choices=[('flat', 'Flat'), ('round', 'Round')], max_length=10, verbose_name='Форма')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='wire.color', verbose_name='Колір')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='wire.manufacturer', verbose_name='Виробник')),
                ('wire_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='wire.wiretype', verbose_name='Тип дроту')),
            ],
            options={
                'verbose_name': 'Варіант дроту',
                'verbose_name_plural': 'Варіанти дротів',
                'db_table': 'wire_variant',
            },
        ),
        migrations.CreateModel(
            name='WirePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_m', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Довжина (м)')),
                ('location', models.CharField(blank=True, max_length=60, null=True, verbose_name='Місце зберігання')),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('reserved', 'Reserved'), ('used', 'Used'), ('scrap', 'Scrap')], default='in_stock', max_length=20, verbose_name='Статус')),
                ('note', models.TextField(blank=True, default='', verbose_name='Нотатка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('wire_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='wire.wirevariant', verbose_name='Варіант дроту')),
            ],
            options={
                'verbose_name': 'Фізичний шматок дроту/проводу',
                'verbose_name_plural': 'Фізичні шматки дротів/проводів',
                'db_table': 'wire_piece',
            },
        ),
        migrations.CreateModel(
            name='WireTypeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wire_types', to='wire.color', verbose_name='Дозволений колір')),
                ('wire_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_colors', to='wire.wiretype', verbose_name='Тип дроту')),
            ],
            options={
                'verbose_name': 'Правило кольору для типу дроту',
                'verbose_name_plural': 'Правила кольорів для типів проводів',
                'db_table': 'wire_type_color',
                'constraints': [models.UniqueConstraint(fields=('wire_type', 'color'), name='uq_wire_type_color')],
            },
        ),
        migrations.AddConstraint(
            model_name='wirevariant',
            constraint=models.UniqueConstraint(fields=('wire_type', 'cores', 'mm2', 'shape', 'manufacturer', 'color'), name='uq_cable_variant'),
        ),
    ]
