# Generated by Django 6.0.4 on 2026-06-04 22:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Колір')),
            ],
            options={
                'verbose_name': 'Колір',
                'verbose_name_plural': 'Кольори',
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Виробник')),
            ],
            options={
                'verbose_name': 'Виробник',
                'verbose_name_plural': 'Виробники',
                'db_table': 'manufacturer',
            },
        ),
        migrations.CreateModel(
            name='WireType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Назва типу')),
            ],
            options={
                'verbose_name': 'Тип дроту/кабелю',
                'verbose_name_plural': 'Типи дротів та кабелів',
                'db_table': 'wire_type',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Адміністратор'), ('manager', 'Менеджер'), ('storeleeper', 'Комірник'), ('viewer', 'Переглядач')], default='viewer', max_length=20, verbose_name='Роль')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Відділ')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Користувач',
                'verbose_name_plural': 'Користувачі',
                'db_table': 'custom_user',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WireVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cores', models.PositiveSmallIntegerField(verbose_name='Кількість жил')),
                ('mm2', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Переріз (мм.кв)')),
                ('shape', models.CharField(choices=[('flat', 'Flat'), ('round', 'Round')], max_length=10, verbose_name='Форма')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='wire.color', verbose_name='Колір')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='wire.manufacturer', verbose_name='Виробник')),
                ('wire_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='wire.wiretype', verbose_name='Тип дроту')),
            ],
            options={
                'verbose_name': 'Варіант дроту',
                'verbose_name_plural': 'Варіанти дротів',
                'db_table': 'wire_variant',
            },
        ),
        migrations.CreateModel(
            name='WirePiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_m', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Довжина (м)')),
                ('location', models.CharField(blank=True, max_length=60, null=True, verbose_name='Місце зберігання')),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('reserved', 'Reserved'), ('used', 'Used'), ('scrap', 'Scrap')], default='in_stock', max_length=20, verbose_name='Статус')),
                ('note', models.TextField(blank=True, default='', verbose_name='Нотатка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
                ('wire_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='wire.wirevariant', verbose_name='Варіант дроту')),
            ],
            options={
                'verbose_name': 'Фізичний шматок дроту/проводу',
                'verbose_name_plural': 'Фізичні шматки дротів/проводів',
                'db_table': 'wire_piece',
            },
        ),
        migrations.CreateModel(
            name='WireTypeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wire_types', to='wire.color', verbose_name='Дозволений колір')),
                ('wire_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_colors', to='wire.wiretype', verbose_name='Тип дроту')),
            ],
            options={
                'verbose_name': 'Правило кольору для типу дроту',
                'verbose_name_plural': 'Правила кольорів для типів проводів',
                'db_table': 'wire_type_color',
                'constraints': [models.UniqueConstraint(fields=('wire_type', 'color'), name='uq_wire_type_color')],
            },
        ),
        migrations.AddConstraint(
            model_name='wirevariant',
            constraint=models.UniqueConstraint(fields=('wire_type', 'cores', 'mm2', 'shape', 'manufacturer', 'color'), name='uq_cable_variant'),
        ),
    ]
